<?php
 $aik =  array (
  'sitename' => '果园影院',
  'pcdomain' => 'http://video.shikexu.com',
  'title' => '果园影院-果园伙伴专供',
  'keywords' => '果园影院,电视直播网站,零八影院快播,高清云影视,云点播,免费看视频,湖南卫视直播,80电影网,最新电影天堂免费在线观看',
  'description' => '果园影院,热剧快播,最好看的剧情片尽在﻿果园影院,高清云影视免费为大家提供最新最全的免费电影,电视剧,综艺,动漫无广告在线云点播,以及电视直播',
//  'icp' => '国ICP备18888888号',
  'icp' => '豫ICP备12022556号',
  'foot' => '本站提供的最新电影和电视剧资源均系收集于各大视频网站,本站只提供web页面服务,并不提供影片资源存储,也不参与录制、上传</br>若本站收录的节目无意侵犯了贵司版权，请给网页底部邮箱地址来信,我们会及时处理和回复,谢谢。',
//  'tongji' => '<script src="https://s13.cnzz.com/z_stat.php?id=1262571414&web_id=1262571414" language="JavaScript"></script>',
  'tongji' => '<script type="text/javascript">var cnzz_protocol = (("https:" == document.location.protocol) ? " https://" : " http://");document.write(unescape("%3Cspan id=\'cnzz_stat_icon_1263118461\'%3E%3C/span%3E%3Cscript src=\'" + cnzz_protocol + "s19.cnzz.com/z_stat.php%3Fid%3D1263118461%26show%3Dpic\' type=\'text/javascript\'%3E%3C/script%3E"));</script>',
  'baidu_push'=>"<script type='text/javascript'>(function(){var bp = document.createElement('script');var curProtocol = window.location.protocol.split(':')[0];if (curProtocol === 'https') {bp.src = 'https://zz.bdstatic.com/linksubmit/push.js';}else {bp.src = 'http://push.zhanzhang.baidu.com/push.js';}var s = document.getElementsByTagName(\"script\")[0];s.parentNode.insertBefore(bp, s);})();</script>",
  'jiekou1' => 'https://api.flvsp.com/?url=',
  'jiekou2' => 'https://api.47ks.com/webcloud/?v=',
  'jiekou3' => 'http://www.efunfilm.com/yunparse/index.php?url=',
  'jiekou4' => 'http://api.nepian.com/ckparse/?url=',
  'jiekou5' => 'http://aikan-tv.com/?url=',
  'jiekou6' => 'http://j.zz22x.com/jx/?url=',
  'jiekou7' => 'http://jiexi.071811.cc/jx2.php?url=',
  'jiekou8' => 'http://api.wlzhan.com/sudu/?url=',
  'jiekou9' => 'http://api.xfsub.com/index.php?url=',
  'jiekou10' => 'http://api.wlzhan.com/sudu/?url=',
  'admin_name' => 'admin',
  'admin_pass' => '196b067faaed758b345a339d5c04d210',
  'admin_email' => '997823131@qq.com',
  'logo_dh' => '<img src="images/logo.png">',
  'logo_ss' => '<img id="imgsrc" src="images/sologo.png">',
  'movie_ad' => '<a href="http://www.diaoyoutx.com" target="_blank"><img src="images/dc5c7986daef50c.gif" style="width:100%"></a>',
  'tv_ad' => '<a href="http://www.diaoyoutx.com" target="_blank"><img src="images/dc5c7986daef50c.gif" style="width:100%"></a>',
  'zongyi_ad' => '<a href="http://www.diaoyoutx.com" target="_blank"><img src="images/dc5c7986daef50c.gif" style="width:100%"></a>',
  'dongman_ad' => '<a href="http://www.diaoyoutx.com" target="_blank"><img src="images/dc5c7986daef50c.gif" style="width:100%"></a>',
  'jiazai_ad' => '<a href="http://www.diaoyoutx.com" target="_blank"><img src="images/jiazai.png" width="100%"></a>',
  'zfb_ad' => '<img src="images/zfb.png">',
  'wx_ad' => '<img src="images/wx.png">',
  'cebian1_ad' => '<a class="style02" href="http://www.diaoyoutx.com" target="_blank"><strong>关注微信</strong><div class="article-wechats"> </br> <img src="images/qrcode.png"></div> </a>',
  'cebian3_ad' => '<h3>广告赞助</h3>			
<div class="textwidget"><a href="http://www.diaoyoutx.com" target="_blank"><img src="images/jianzhi.png" width="100%"></a>',
  'weixin_ad' => '<img src="images/qrcode.png">',
  'end_ad' => '<a href="http://www.diaoyoutx.com"><span><img src="/images/gouwu.png"/>购物</span></a>',
  'hometopnotice' => '',
  'hometopright' => '',
  'homelink' => '',
  'sort' => '1,2,3,4,5,6,7,8,9,10',
  'joinhotkey' => '0',
);
?>